services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
  backend:
    image: github.com/otherband/express-recommend
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - 8085:8085
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: postgres, dev

  frontend:
    image: github.com/otherband/express-recommend-frontend
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - 8080:80
    depends_on:
      - backend