name: Verify Code
on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'
      - 'enhancement'
jobs:
  verify_backend:
    name: Verify Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "JDK set-up"
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: mvn clean verify
  verify_frontend:
    name: Verify Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Node set-up"
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: cd frontend && npm install
      - name: Build
        run: cd frontend && npm run build -- --mode=production
