name: Verify Code
on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'
jobs:
  verify_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "JDK set-up"
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: mvn verify
